const express = require("express");
const PDFDocument = require("pdfkit");
const TowerDump = require("../models/TowerDump");

const router = express.Router();

router.get("/:number", async (req, res) => {
  try {
    const number = req.params.number;

    const records = await TowerDump.find({
      mobileNumber: number,
    }).sort({ timestamp: 1 });

    if (records.length === 0) {
      return res.status(404).json({
        message: "No records found",
      });
    }

    const doc = new PDFDocument({
      margin: 50,
    });

    res.setHeader(
      "Content-Type",
      "application/pdf"
    );

    res.setHeader(
      "Content-Disposition",
      `attachment; filename=${number}-report.pdf`
    );

    doc.pipe(res);

    // ==========================
    // HEADER
    // ==========================

    doc
      .fontSize(24)
      .text(
        "Tower Dump Investigation Report",
        {
          align: "center",
        }
      );

    doc.moveDown();

    doc
      .fontSize(12)
      .text(
        `Generated On: ${new Date().toLocaleString()}`
      );

    doc.text(
      `Investigation ID: INV-${Date.now()}`
    );

    doc.moveDown();

    // ==========================
    // SUSPECT DETAILS
    // ==========================

    doc
      .fontSize(18)
      .text("Suspect Information");

    doc.moveDown(0.5);

    doc
      .fontSize(12)
      .text(`Mobile Number: ${number}`);

    doc.text(
      `Total Appearances: ${records.length}`
    );

    doc.moveDown();

    // ==========================
    // RISK LEVEL
    // ==========================

    let riskLevel = "LOW";

    if (records.length >= 3)
      riskLevel = "MEDIUM";

    if (records.length >= 5)
      riskLevel = "HIGH";

    doc
      .fontSize(18)
      .text("Risk Assessment");

    doc.moveDown(0.5);

    doc
      .fontSize(12)
      .text(`Risk Level: ${riskLevel}`);

    doc.moveDown();

    // ==========================
    // EXECUTIVE SUMMARY
    // ==========================

    doc
      .fontSize(18)
      .text("Executive Summary");

    doc.moveDown(0.5);

    doc
      .fontSize(12)
      .text(
        `The suspect mobile number ${number} was detected ${records.length} times across analyzed tower dump records. The movement history and location traces indicate potential travel patterns that may assist investigators in narrowing down suspect activity.`
      );

    doc.moveDown();

    // ==========================
    // MOVEMENT TIMELINE
    // ==========================

    doc
      .fontSize(18)
      .text("Movement Timeline");

    doc.moveDown(0.5);

    records.forEach((record, index) => {
      doc
        .fontSize(12)
        .text(
          `${index + 1}. Tower ID: ${
            record.towerId
          }`
        );

      doc.text(
        `    Time: ${new Date(
          record.timestamp
        ).toLocaleString()}`
      );

      doc.text(
        `    Location: (${record.latitude}, ${record.longitude})`
      );

      doc.moveDown(0.5);
    });

    doc.moveDown();

    // ==========================
    // LOCATION HISTORY
    // ==========================

    doc
      .fontSize(18)
      .text("Location History");

    doc.moveDown(0.5);

    records.forEach((record, index) => {
      doc
        .fontSize(12)
        .text(
          `${index + 1}. Latitude: ${record.latitude} | Longitude: ${record.longitude}`
        );
    });

    doc.moveDown();

    // ==========================
    // CONCLUSION
    // ==========================

    doc
      .fontSize(18)
      .text("Investigation Conclusion");

    doc.moveDown(0.5);

    doc
      .fontSize(12)
      .text(
        `Based on tower dump analysis, the suspect device demonstrates repeated presence across monitored locations. Further forensic analysis and cross-referencing with additional evidence sources is recommended.`
      );

    doc.moveDown(2);

    doc.text(
      "Generated by Tower Dump Analysis System",
      {
        align: "center",
      }
    );

    doc.end();
  } catch (error) {
    res.status(500).json({
      message: error.message,
    });
  }
});

module.exports = router;